/* Generated by Yosys 0.38+75 (git sha1 01d6c12af, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module UART_Receiver(i_clock, i_RX_Serial, o_RX_Byte, o_RX_Done);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire [2:0] _263_;
  wire [2:0] _264_;
  wire [2:0] _265_;
  wire [7:0] _266_;
  input i_RX_Serial;
  wire i_RX_Serial;
  input i_clock;
  wire i_clock;
  output [7:0] o_RX_Byte;
  wire [7:0] o_RX_Byte;
  output o_RX_Done;
  wire o_RX_Done;
  reg [7:0] r_RX_Byte = 8'h00;
  reg r_RX_Data = 1'h1;
  reg r_RX_Data1 = 1'h1;
  reg r_RX_Done;
  reg [2:0] r_SM_main = 3'h0;
  reg [2:0] r_bit_index = 3'h0;
  reg [7:0] r_clock_count = 8'h00;
  sky130_fd_sc_hd__clkinv_1 _267_ (
    .A(_252_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__or2_0 _268_ (
    .A(_249_),
    .B(_250_),
    .X(_172_)
  );
  sky130_fd_sc_hd__nor2b_1 _269_ (
    .A(_251_),
    .B_N(_250_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nand2b_1 _270_ (
    .A_N(_249_),
    .B(_198_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__nor2_1 _271_ (
    .A(_262_),
    .B(_261_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__a21o_1 _272_ (
    .A1(_257_),
    .A2(_256_),
    .B1(_258_),
    .X(_201_)
  );
  sky130_fd_sc_hd__a211oi_1 _273_ (
    .A1(_259_),
    .A2(_201_),
    .B1(_262_),
    .C1(_260_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__or2_0 _274_ (
    .A(_200_),
    .B(_202_),
    .X(_203_)
  );
  sky130_fd_sc_hd__nor2_1 _275_ (
    .A(_199_),
    .B(_203_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__o22ai_1 _276_ (
    .A1(_251_),
    .A2(_172_),
    .B1(_199_),
    .B2(_203_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor3b_1 _277_ (
    .A(_250_),
    .B(_251_),
    .C_N(_249_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__or3b_1 _278_ (
    .A(_250_),
    .B(_251_),
    .C_N(_249_),
    .X(_205_)
  );
  sky130_fd_sc_hd__nand2_1 _279_ (
    .A(_256_),
    .B(_255_),
    .Y(_206_)
  );
  sky130_fd_sc_hd__and4b_1 _280_ (
    .A_N(_257_),
    .B(_256_),
    .C(_255_),
    .D(_260_),
    .X(_207_)
  );
  sky130_fd_sc_hd__nand4b_1 _281_ (
    .A_N(_259_),
    .B(_258_),
    .C(_200_),
    .D(_207_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__clkinv_1 _282_ (
    .A(_208_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__a31oi_1 _283_ (
    .A1(_248_),
    .A2(_204_),
    .A3(_209_),
    .B1(_251_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__nand2_1 _284_ (
    .A(_249_),
    .B(_198_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nor2_1 _285_ (
    .A(_203_),
    .B(_210_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__o21ai_0 _286_ (
    .A1(_203_),
    .A2(_210_),
    .B1(_172_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nand2_1 _287_ (
    .A(_253_),
    .B(_252_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__nand3_1 _288_ (
    .A(_253_),
    .B(_252_),
    .C(_254_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__nand2b_1 _289_ (
    .A_N(_199_),
    .B(_212_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__or4_1 _290_ (
    .A(_199_),
    .B(_200_),
    .C(_202_),
    .D(_212_),
    .X(_213_)
  );
  sky130_fd_sc_hd__o21ai_0 _291_ (
    .A1(_200_),
    .A2(_202_),
    .B1(_198_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__o21bai_1 _292_ (
    .A1(_200_),
    .A2(_202_),
    .B1_N(_210_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__nand2_1 _293_ (
    .A(_204_),
    .B(_208_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__or3_1 _294_ (
    .A(_251_),
    .B(_248_),
    .C(_172_),
    .X(_217_)
  );
  sky130_fd_sc_hd__o21ai_0 _295_ (
    .A1(_248_),
    .A2(_208_),
    .B1(_204_),
    .Y(_218_)
  );
  sky130_fd_sc_hd__nand4_1 _296_ (
    .A(_213_),
    .B(_215_),
    .C(_217_),
    .D(_218_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__or3_1 _297_ (
    .A(_248_),
    .B(_205_),
    .C(_208_),
    .X(_219_)
  );
  sky130_fd_sc_hd__nand3_1 _298_ (
    .A(_199_),
    .B(_214_),
    .C(_219_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__a21oi_1 _299_ (
    .A1(_205_),
    .A2(_214_),
    .B1(_255_),
    .Y(_232_)
  );
  sky130_fd_sc_hd__xnor2_1 _300_ (
    .A(_256_),
    .B(_255_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__a21oi_1 _301_ (
    .A1(_205_),
    .A2(_214_),
    .B1(_220_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__xor2_1 _302_ (
    .A(_257_),
    .B(_206_),
    .X(_221_)
  );
  sky130_fd_sc_hd__a21oi_1 _303_ (
    .A1(_214_),
    .A2(_216_),
    .B1(_221_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__and4_1 _304_ (
    .A(_258_),
    .B(_257_),
    .C(_256_),
    .D(_255_),
    .X(_222_)
  );
  sky130_fd_sc_hd__a31oi_1 _305_ (
    .A1(_257_),
    .A2(_256_),
    .A3(_255_),
    .B1(_258_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__a211oi_1 _306_ (
    .A1(_214_),
    .A2(_216_),
    .B1(_222_),
    .C1(_223_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__nand2_1 _307_ (
    .A(_259_),
    .B(_222_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__xnor2_1 _308_ (
    .A(_259_),
    .B(_222_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__a21oi_1 _309_ (
    .A1(_205_),
    .A2(_214_),
    .B1(_225_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__xor2_1 _310_ (
    .A(_260_),
    .B(_224_),
    .X(_226_)
  );
  sky130_fd_sc_hd__a21oi_1 _311_ (
    .A1(_214_),
    .A2(_216_),
    .B1(_226_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__and4_1 _312_ (
    .A(_261_),
    .B(_260_),
    .C(_259_),
    .D(_222_),
    .X(_227_)
  );
  sky130_fd_sc_hd__a31oi_1 _313_ (
    .A1(_260_),
    .A2(_259_),
    .A3(_222_),
    .B1(_261_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__a211oi_1 _314_ (
    .A1(_205_),
    .A2(_214_),
    .B1(_227_),
    .C1(_228_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__o21ai_0 _315_ (
    .A1(_262_),
    .A2(_227_),
    .B1(_204_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__a21oi_1 _316_ (
    .A1(_262_),
    .A2(_227_),
    .B1(_189_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__nor2_1 _317_ (
    .A(_253_),
    .B(_252_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__xor2_1 _318_ (
    .A(_253_),
    .B(_252_),
    .X(_187_)
  );
  sky130_fd_sc_hd__nor3_1 _319_ (
    .A(_253_),
    .B(_252_),
    .C(_254_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__mux2_1 _320_ (
    .A0(_240_),
    .A1(_248_),
    .S(_191_),
    .X(_178_)
  );
  sky130_fd_sc_hd__nor3_1 _321_ (
    .A(_253_),
    .B(_186_),
    .C(_254_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__mux2_1 _322_ (
    .A0(_241_),
    .A1(_248_),
    .S(_192_),
    .X(_179_)
  );
  sky130_fd_sc_hd__nor3b_1 _323_ (
    .A(_252_),
    .B(_254_),
    .C_N(_253_),
    .Y(_193_)
  );
  sky130_fd_sc_hd__mux2_1 _324_ (
    .A0(_242_),
    .A1(_248_),
    .S(_193_),
    .X(_180_)
  );
  sky130_fd_sc_hd__nor2_1 _325_ (
    .A(_254_),
    .B(_211_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__mux2_1 _326_ (
    .A0(_243_),
    .A1(_248_),
    .S(_194_),
    .X(_181_)
  );
  sky130_fd_sc_hd__nand2_1 _327_ (
    .A(_254_),
    .B(_190_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__mux2_1 _328_ (
    .A0(_248_),
    .A1(_244_),
    .S(_195_),
    .X(_182_)
  );
  sky130_fd_sc_hd__nand3b_1 _329_ (
    .A_N(_253_),
    .B(_252_),
    .C(_254_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__mux2_1 _330_ (
    .A0(_248_),
    .A1(_245_),
    .S(_196_),
    .X(_183_)
  );
  sky130_fd_sc_hd__nand3_1 _331_ (
    .A(_253_),
    .B(_186_),
    .C(_254_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__mux2_1 _332_ (
    .A0(_248_),
    .A1(_246_),
    .S(_197_),
    .X(_184_)
  );
  sky130_fd_sc_hd__mux2_1 _333_ (
    .A0(_248_),
    .A1(_247_),
    .S(_212_),
    .X(_185_)
  );
  sky130_fd_sc_hd__xnor2_1 _334_ (
    .A(_254_),
    .B(_211_),
    .Y(_188_)
  );
  always @(posedge i_clock)
    r_RX_Data1 <= i_RX_Serial;
  always @(posedge i_clock)
    r_RX_Data <= r_RX_Data1;
  always @(posedge i_clock)
    if (_002_) r_RX_Done <= _000_;
  always @(posedge i_clock)
    if (_001_) r_RX_Byte[0] <= _164_;
  always @(posedge i_clock)
    if (_001_) r_RX_Byte[1] <= _165_;
  always @(posedge i_clock)
    if (_001_) r_RX_Byte[2] <= _166_;
  always @(posedge i_clock)
    if (_001_) r_RX_Byte[3] <= _167_;
  always @(posedge i_clock)
    if (_001_) r_RX_Byte[4] <= _168_;
  always @(posedge i_clock)
    if (_001_) r_RX_Byte[5] <= _169_;
  always @(posedge i_clock)
    if (_001_) r_RX_Byte[6] <= _170_;
  always @(posedge i_clock)
    if (_001_) r_RX_Byte[7] <= _171_;
  always @(posedge i_clock)
    if (_003_)
      if (_005_) r_bit_index[0] <= 1'h0;
      else r_bit_index[0] <= _263_[0];
  always @(posedge i_clock)
    if (_003_)
      if (_005_) r_bit_index[1] <= 1'h0;
      else r_bit_index[1] <= _264_[1];
  always @(posedge i_clock)
    if (_003_)
      if (_005_) r_bit_index[2] <= 1'h0;
      else r_bit_index[2] <= _264_[2];
  always @(posedge i_clock)
    r_SM_main[0] <= _265_[0];
  always @(posedge i_clock)
    r_SM_main[1] <= _265_[1];
  always @(posedge i_clock)
    r_SM_main[2] <= _265_[2];
  always @(posedge i_clock)
    if (_004_) r_clock_count[0] <= _266_[0];
  always @(posedge i_clock)
    if (_004_) r_clock_count[1] <= _266_[1];
  always @(posedge i_clock)
    if (_004_) r_clock_count[2] <= _266_[2];
  always @(posedge i_clock)
    if (_004_) r_clock_count[3] <= _266_[3];
  always @(posedge i_clock)
    if (_004_) r_clock_count[4] <= _266_[4];
  always @(posedge i_clock)
    if (_004_) r_clock_count[5] <= _266_[5];
  always @(posedge i_clock)
    if (_004_) r_clock_count[6] <= _266_[6];
  always @(posedge i_clock)
    if (_004_) r_clock_count[7] <= _266_[7];
  assign _263_[2:1] = r_bit_index[2:1];
  assign _264_[0] = _263_[0];
  assign o_RX_Byte = r_RX_Byte;
  assign o_RX_Done = r_RX_Done;
  assign _262_ = r_clock_count[7];
  assign _261_ = r_clock_count[6];
  assign _260_ = r_clock_count[5];
  assign _259_ = r_clock_count[4];
  assign _258_ = r_clock_count[3];
  assign _257_ = r_clock_count[2];
  assign _256_ = r_clock_count[1];
  assign _255_ = r_clock_count[0];
  assign _249_ = r_SM_main[0];
  assign _250_ = r_SM_main[1];
  assign _251_ = r_SM_main[2];
  assign _000_ = _172_;
  assign _003_ = _175_;
  assign _248_ = r_RX_Data;
  assign _004_ = _176_;
  assign _001_ = _173_;
  assign _002_ = _174_;
  assign _253_ = r_bit_index[1];
  assign _252_ = r_bit_index[0];
  assign _254_ = r_bit_index[2];
  assign _005_ = _177_;
  assign _265_[0] = _229_;
  assign _265_[1] = _230_;
  assign _265_[2] = _231_;
  assign _266_[0] = _232_;
  assign _266_[1] = _233_;
  assign _266_[2] = _234_;
  assign _266_[3] = _235_;
  assign _266_[4] = _236_;
  assign _266_[5] = _237_;
  assign _266_[6] = _238_;
  assign _266_[7] = _239_;
  assign _263_[0] = _186_;
  assign _264_[1] = _187_;
  assign _240_ = r_RX_Byte[0];
  assign _164_ = _178_;
  assign _241_ = r_RX_Byte[1];
  assign _165_ = _179_;
  assign _242_ = r_RX_Byte[2];
  assign _166_ = _180_;
  assign _243_ = r_RX_Byte[3];
  assign _167_ = _181_;
  assign _244_ = r_RX_Byte[4];
  assign _168_ = _182_;
  assign _245_ = r_RX_Byte[5];
  assign _169_ = _183_;
  assign _246_ = r_RX_Byte[6];
  assign _170_ = _184_;
  assign _247_ = r_RX_Byte[7];
  assign _171_ = _185_;
  assign _264_[2] = _188_;
endmodule
